//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushiGo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SushiGo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string ChangePasswordPage_Back {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de 6 dígitos.
        /// </summary>
        public static string ChangePasswordPage_Code {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string ChangePasswordPage_Email {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para cambiar la contraseña, ingresa el código de 6 dígitos que se te envió a tu correo electrónico.
        /// </summary>
        public static string ChangePasswordPage_Instructions {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string ChangePasswordPage_Title {
            get {
                return ResourceManager.GetString("ChangePasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear cuenta.
        /// </summary>
        public static string CreateAccountPage_CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccountPage_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string CreateAccountPage_Email {
            get {
                return ResourceManager.GetString("CreateAccountPage_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CreateAccountPage_Name {
            get {
                return ResourceManager.GetString("CreateAccountPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string CreateAccountPage_Password {
            get {
                return ResourceManager.GetString("CreateAccountPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear cuenta.
        /// </summary>
        public static string CreateAccountPage_Title {
            get {
                return ResourceManager.GetString("CreateAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string CreateAccountPage_Username {
            get {
                return ResourceManager.GetString("CreateAccountPage_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string LoginPage_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginPage_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LoginPage_LogIn {
            get {
                return ResourceManager.GetString("LoginPage_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo / Nombre de usuario.
        /// </summary>
        public static string LoginPage_LoginMethod {
            get {
                return ResourceManager.GetString("LoginPage_LoginMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string LoginPage_Password {
            get {
                return ResourceManager.GetString("LoginPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string LoginPage_Title {
            get {
                return ResourceManager.GetString("LoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string StartPage_Language {
            get {
                return ResourceManager.GetString("StartPage_Language", resourceCulture);
            }
        }
    }
}
